services:
  - type: web
    name: my-node-api          
    env: node
    plan: free              
    branch: main
    region: oregon            

    runtime: node
    nodeVersion: 20           

    buildCommand: npm install
    startCommand: node index.js

    autoDeploy: true          



    envVars:
      - key: NODE_ENV
        value: production

startCommand: npm run dev
